// ignore_for_file: avoid_print
//
// Builds the glyph fonts from assets/svgs/.
//
// Run from package root:
//   dart run tool/build_font.dart
//
// Outputs:
//   lib/fonts/Glyphs<Style>.ttf      — generated font files
//   assets/codepoints.json           — name -> codepoint map (deterministic)
//   assets/metadata.json             — fuller metadata
//   lib/src/glyphs.g.dart            — Dart IconData constants
//   lib/src/glyph_offsets.g.dart     — mass-center delta map

import 'dart:convert';
import 'dart:io';

const _package = 'glyphs';
const _svgRoot = 'assets/svgs';
const _fontsDir = 'lib/fonts';
const _codepointsPath = 'assets/codepoints.json';
const _metadataPath = 'assets/metadata.json';
const _generatedDart = 'lib/src/glyphs.g.dart';
const _generatedOffsets = 'lib/src/glyph_offsets.g.dart';
const _offsetsJson = 'assets/offsets.json';
const _pythonScript = 'tool/build_font.py';
const _measureScript = 'tool/measure_offsets.dart';

// Style -> font family. Base codepoints and range sizes are derived from
// the actual SVG counts at build time, packed sequentially starting at the
// Unicode Private Use Area (U+E000).
const _styles = <String, String>{
  'solid': 'GlyphsSolid',
  'regular': 'GlyphsRegular',
  'brands': 'GlyphsBrands',
};

Future<void> main() async {
  await _checkPython();

  // 1. Discover SVGs and allocate (base, range) per style from counts.
  const puaStart = 0xE000; // Unicode Private Use Area.
  final names = <String, List<String>>{};
  final bases = <String, int>{};
  final ranges = <String, int>{};
  var cursor = puaStart;
  for (final style in _styles.keys) {
    final dir = Directory('$_svgRoot/$style');
    if (!dir.existsSync()) {
      stderr.writeln('ERROR: missing $_svgRoot/$style');
      exit(2);
    }
    final list = dir
        .listSync()
        .whereType<File>()
        .where((f) => f.path.endsWith('.svg'))
        .map((f) => f.uri.pathSegments.last.replaceAll('.svg', ''))
        .toList()
      ..sort();
    names[style] = list;
    bases[style] = cursor;
    ranges[style] = list.length;
    cursor += list.length;
    final lo = bases[style]!.toRadixString(16).toUpperCase();
    final hi = (cursor - 1).toRadixString(16).toUpperCase();
    print('  $style: ${list.length} icons (U+$lo..U+$hi)');
  }

  // 2. Hash-assign codepoints per style.
  final assigned = <String, Map<String, int>>{};
  for (final style in _styles.keys) {
    final base = bases[style]!;
    final range = ranges[style]!;
    final list = names[style]!;

    final taken = <int>{};
    final out = <String, int>{};
    for (final name in list) {
      var slot = _fnv1a(name) % range;
      while (taken.contains(slot)) {
        slot = (slot + 1) % range;
      }
      taken.add(slot);
      out[name] = base + slot;
    }
    assigned[style] = out;
  }

  // 2. Persist codepoints.json (sorted by name for stable diffs).
  Directory('assets').createSync(recursive: true);
  final ordered = <String, Map<String, String>>{};
  for (final s in _styles.keys) {
    final m = assigned[s]!;
    final keys = m.keys.toList()..sort();
    ordered[s] = {
      for (final k in keys) k: '0x${m[k]!.toRadixString(16).toUpperCase()}',
    };
  }
  File(_codepointsPath).writeAsStringSync(
    const JsonEncoder.withIndent('  ').convert(ordered),
  );

  // 3. Build font via python.
  Directory(_fontsDir).createSync(recursive: true);
  final spec = {
    'styles': [
      for (final e in _styles.entries)
        {
          'name': e.key,
          'family': e.value,
          'svgDir': '$_svgRoot/${e.key}',
          'codepoints': assigned[e.key],
          'outPath': '$_fontsDir/${e.value}.ttf',
        },
    ],
  };
  final specFile =
      File('${Directory.systemTemp.path}/icons_build_spec.json')
        ..writeAsStringSync(jsonEncode(spec));

  print('building fonts...');
  final result = await Process.run('python3', [_pythonScript, specFile.path]);
  stdout.write(result.stdout);
  stderr.write(result.stderr);
  if (result.exitCode != 0) {
    exitCode = result.exitCode;
    return;
  }

  // 4. Measure mass-center offsets via flutter test.
  print('measuring mass-center offsets...');
  final measure = await Process.start(
    'flutter',
    ['test', _measureScript],
    mode: ProcessStartMode.inheritStdio,
  );
  final measureExit = await measure.exitCode;
  if (measureExit != 0) {
    stderr.writeln('ERROR: measurement step failed (exit $measureExit)');
    exitCode = measureExit;
    return;
  }

  // 4b. Generate lib/src/icon_offsets.g.dart from offsets.json.
  final offsetsRaw =
      jsonDecode(File(_offsetsJson).readAsStringSync()) as Map<String, dynamic>;
  final offBuf = StringBuffer()
    ..writeln('// GENERATED BY tool/build_font.dart — DO NOT EDIT.')
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln('/// Mass-center correction per glyph, in em-fractions.')
    ..writeln('/// Glyph(blend: 1) shifts the glyph by Offset * size.')
    ..writeln('const Map<int, Offset> kGlyphMassDelta = {');
  final offEntries = offsetsRaw.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  for (final e in offEntries) {
    final cp = int.parse(e.key.substring(2), radix: 16);
    final v = e.value as List<dynamic>;
    offBuf.writeln(
      '  0x${cp.toRadixString(16)}: Offset(${v[0]}, ${v[1]}),',
    );
  }
  offBuf.writeln('};');
  File(_generatedOffsets).writeAsStringSync(offBuf.toString());
  print('wrote $_generatedOffsets (${offEntries.length} entries)');

  // 5. metadata.json (richer view).
  final meta = {
    'styles': [
      for (final e in _styles.entries)
        {
          'name': e.key,
          'family': e.value,
          'asset': '$_fontsDir/${e.value}.ttf',
          'icons': [
            for (final i
                in (assigned[e.key]!.entries.toList()
                  ..sort((a, b) => a.key.compareTo(b.key))))
              {
                'name': i.key,
                'codepoint': '0x${i.value.toRadixString(16).toUpperCase()}',
              },
          ],
        },
    ],
  };
  File(
    _metadataPath,
  ).writeAsStringSync(const JsonEncoder.withIndent('  ').convert(meta));

  // 6. Generate lib/src/glyphs.g.dart.
  Directory('lib/src').createSync(recursive: true);
  final buf = StringBuffer()
    ..writeln('// GENERATED BY tool/build_font.dart — DO NOT EDIT.')
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln();
  for (final e in _styles.entries) {
    final style = e.key;
    final family = e.value;
    final className = 'Glyphs${_pascal(style)}';
    buf.writeln('class $className {');
    buf.writeln('  $className._();');
    final entries = assigned[style]!.entries.toList()
      ..sort((a, b) => a.key.compareTo(b.key));
    for (final ic in entries) {
      final id = _dartIdent(ic.key);
      final hex = '0x${ic.value.toRadixString(16)}';
      buf.writeln(
        "  static const IconData $id = IconData($hex, fontFamily: '$family', fontPackage: '$_package');",
      );
    }
    buf.writeln('}');
    buf.writeln();
  }
  File(_generatedDart).writeAsStringSync(buf.toString());

  print('done.');
  print('');
  print('Add the following to pubspec.yaml under flutter:fonts if not present:');
  for (final e in _styles.entries) {
    final family = e.value;
    print('  - family: $family');
    print('    fonts:');
    print('      - asset: $_fontsDir/$family.ttf');
  }
}

int _fnv1a(String s) {
  var h = 0x811c9dc5;
  for (final c in s.codeUnits) {
    h ^= c;
    h = (h * 0x01000193) & 0xFFFFFFFF;
  }
  return h;
}

Future<void> _checkPython() async {
  String? pyErr;
  try {
    final r = await Process.run('python3', ['--version']);
    if (r.exitCode != 0) pyErr = 'python3 returned exit ${r.exitCode}';
  } catch (e) {
    pyErr = '$e';
  }
  if (pyErr != null) {
    stderr.writeln(
      'ERROR: python3 not found ($pyErr).\n\n'
      'Install with:\n'
      '  macOS:  brew install python\n'
      '  Linux:  apt install python3\n',
    );
    exit(2);
  }
  final r = await Process.run('python3', ['-c', 'import fontTools']);
  if (r.exitCode != 0) {
    stderr.writeln(
      'ERROR: fontTools (Python package) is not installed.\n\n'
      'Install with:\n'
      '  pip3 install fonttools\n\n'
      'Or in a venv:\n'
      '  python3 -m venv .venv\n'
      '  source .venv/bin/activate\n'
      '  pip install fonttools\n',
    );
    exit(2);
  }
}

String _pascal(String s) =>
    s.split('_').map((p) => p[0].toUpperCase() + p.substring(1)).join();

const _reserved = {
  'class', 'switch', 'default', 'if', 'else', 'true', 'false', 'null', //
  'new', 'this', 'super', 'return', 'for', 'in', 'is', 'as', 'do', //
  'while', 'break', 'continue', 'void', 'var', 'final', 'const', 'enum', //
  'extends', 'implements', 'with', 'try', 'catch', 'throw', 'assert',
};

String _dartIdent(String name) {
  var s = name.replaceAll('-', '_').replaceAll('.', '_');
  if (RegExp(r'^\d').hasMatch(s)) s = 'n$s';
  if (_reserved.contains(s)) s = '${s}_';
  return s;
}
